### ISSUE TITLE
📋 MCP Server Specification Format Definition

### ISSUE THREAD

**Issue by milliondreams** [rustic-ai/codeprism#119]
## Task Description
Define standardized YAML/JSON format for MCP server specifications to enable data-driven testing of any MCP server implementation.

## Acceptance Criteria
- [ ] JSON schema for server specification format
- [ ] YAML structure for server capabilities, tools, resources, prompts
- [ ] Tool input/output schema definitions
- [ ] Test case specification format
- [ ] Performance expectation definitions
- [ ] Example specifications for multiple server types

## Specification Components
- **Server Metadata**: Name, version, capabilities, transport mechanisms
- **Tool Definitions**: Name, description, input schema, output schema
- **Test Cases**: Input data, expected outputs, performance requirements
- **Resource Definitions**: Available resources and their schemas
- **Prompt Definitions**: Available prompts and their parameter schemas

## Example Structure
```yaml
# server.yaml
name: "Example MCP Server"
version: "1.0.0"
capabilities:
  tools: true
  resources: true
  prompts: false

tools:
  - name: "example_tool"
    description: "Example tool description"
    input_schema: "./schemas/example_tool_input.json"
    output_schema: "./schemas/example_tool_output.json"
    test_cases: "./tests/example_tool_tests.yaml"

transport: "stdio"
server_command: "node server.js"
```

## Key Benefits
- Server-agnostic test harness
- Data-driven test case management
- Easy addition of new servers and tools
- Version-controlled test specifications
- Community-contributable server specs

## Technical Requirements
- JSON Schema validation for spec format
- YAML parsing and validation
- Schema composition and referencing
- Clear error messages for invalid specs

Part of Generic MCP Test Harness - Protocol specification.
