### ISSUE TITLE
🔧 CodePrism MCP Server Specification

### ISSUE THREAD

**Issue by milliondreams** [rustic-ai/codeprism#120]
## Task Description
Create comprehensive YAML specification files for CodePrism MCP server tools, moving tool-specific knowledge out of the generic test harness into data files.

## Acceptance Criteria
- [ ] CodePrism server specification (server.yaml)
- [ ] Individual tool specification files for all 26+ tools
- [ ] JSON schemas for tool input/output validation
- [ ] Test case definitions for comprehensive tool testing
- [ ] Performance benchmarks and expectations
- [ ] Multi-language test data integration

## Tools to Specify (26+ tools)
**Core Tools (6)**: repository_stats, trace_path, find_dependencies, find_references, explain_symbol, search_symbols
**Search Tools (4)**: search_content, find_files, content_stats, detect_patterns  
**Analysis Tools (13)**: analyze_complexity, trace_data_flow, analyze_transitive_dependencies, trace_inheritance, analyze_decorators, find_duplicates, find_unused_code, analyze_security, analyze_performance, analyze_api_surface, analyze_javascript_frameworks, analyze_react_components, analyze_nodejs_patterns
**Workflow Tools (3)**: suggest_analysis_workflow, batch_analysis, optimize_workflow

## File Structure
```
specs/codeprism/
├── server.yaml                    # Main server specification
├── schemas/                       # JSON schemas for tool I/O
│   ├── repository_stats_input.json
│   ├── repository_stats_output.json
│   ├── analyze_security_input.json
│   └── analyze_security_output.json
├── tests/                         # Test case definitions
│   ├── repository_stats_tests.yaml
│   ├── analyze_security_tests.yaml
│   └── find_duplicates_tests.yaml
└── test-data/                     # Sample projects for testing
    ├── python-sample/
    ├── rust-sample/
    └── javascript-sample/
```

## Example Tool Specification
```yaml
# tests/analyze_security_tests.yaml
test_cases:
  - name: "basic_security_scan"
    description: "Basic OWASP vulnerability detection"
    input:
      analysis_type: "comprehensive"
      severity_threshold: "medium"
    expected_schema: "analyze_security_output.json"
    expected_fields:
      - path: "$.vulnerabilities"
        type: "array"
        min_length: 0
      - path: "$.total_findings"
        type: "number"
        minimum: 0
    performance:
      max_duration_ms: 10000
      max_memory_mb: 512
```

## Migration from Current Implementation
- Extract test cases from current Rust code to YAML
- Convert hardcoded expectations to JSON schemas
- Migrate test data to separate files
- Update test harness to load specifications

## Benefits
- Tool tests maintainable without Rust knowledge
- Easy addition of new tools and test cases
- Version-controlled test specifications
- Reusable across different test harnesses
- Clear separation of concerns

Part of Generic MCP Test Harness - CodePrism server specification.
