### ISSUE TITLE
Add build system integration documentation for new parsers

### ISSUE THREAD

**Issue by milliondreams** [rustic-ai/codeprism#25]
## Problem
The Parser Specification document is missing critical build system integration information. Developers don't know how to properly integrate new parsers into the workspace build system.

## Missing Documentation
- **Workspace Registration**: How to add new parser to `Cargo.toml` members array
- **Dependency Management**: Using workspace-level dependency coordination
- **Tree-sitter Grammar Integration**: How to embed/link grammar files properly
- **Build Configuration**: `build.rs` patterns for grammar compilation
- **Cross-crate Dependencies**: How parsers interact with core crates
- **Release Coordination**: Version management across workspace

## Current Build System Analysis
```toml
# Root Cargo.toml shows workspace pattern
[workspace]
members = [
    "crates/codeprism-core",
    "crates/codeprism-lang-js",
    "crates/codeprism-lang-python",
    # New parsers need to be added here
]

[workspace.dependencies]
tree-sitter = "0.24"
tree-sitter-python = "0.23"
# Grammar dependencies managed at workspace level
```

## Acceptance Criteria
- [ ] Add "Build System Integration" section to PARSER_SPECIFICATION.md
- [ ] Document workspace registration process
- [ ] Explain workspace dependency management
- [ ] Show `build.rs` patterns for grammar compilation
- [ ] Document `deny.toml` compliance requirements
- [ ] Add troubleshooting guide for build issues
- [ ] Provide template `Cargo.toml` with proper workspace integration
- [ ] Document release coordination process

## Priority
Critical - Required for proper parser integration
