### ISSUE TITLE
Create configuration-driven parsing system

### ISSUE THREAD

**Issue by milliondreams** [rustic-ai/codeprism#28]
## Problem
Parser AST mapping logic is currently hardcoded in Rust, making it difficult to:
- Quickly prototype new language support
- Adjust node mappings without recompilation
- Share mapping configurations between parsers
- Enable non-Rust developers to contribute language support

## Proposed Solution
Implement a configuration-driven parsing system using declarative mapping files:

```yaml
# parser-config.yml
language: rust
extensions: [rs, rlib]
tree_sitter_grammar: tree-sitter-rust

node_mappings:
  function_item: Function
  struct_item: Class
  impl_item: Method
  call_expression: Call
  use_declaration: Import
  
edge_mappings:
  call_expression->function_item: Calls
  impl_item->struct_item: Implements
  use_declaration->crate: Imports

span_extraction:
  function_item: 
    name_field: "name"
    parameters_field: "parameters"
  struct_item:
    name_field: "name"
    type_parameters_field: "type_parameters"

metadata_extraction:
  function_item:
    visibility: "visibility_modifier"
    return_type: "return_type"
    is_async: "async_keyword"
```

### 1. Configuration Parser
```rust
pub struct ParserConfig {
    pub language: String,
    pub extensions: Vec<String>,
    pub node_mappings: HashMap<String, NodeKind>,
    pub edge_mappings: Vec<EdgeMapping>,
    pub span_extraction: HashMap<String, SpanConfig>,
    pub metadata_extraction: HashMap<String, MetadataConfig>,
}
```

### 2. Generic Configuration-Driven Parser
```rust
pub struct ConfigurableParser {
    pub fn from_config(config: ParserConfig) -> Result<Self>;
    pub fn parse_with_config(&mut self, context: &ParseContext) -> Result<ParseResult>;
}
```

### 3. Configuration Validation
```rust
pub struct ConfigValidator {
    pub fn validate_config(&self, config: &ParserConfig) -> ValidationResult;
    pub fn check_node_mappings(&self, mappings: &HashMap<String, NodeKind>) -> MappingResult;
    pub fn validate_edge_rules(&self, edges: &[EdgeMapping]) -> EdgeResult;
}
```

## Advanced Features
- **Hot Reloading**: Update configurations without restart
- **Inheritance**: Base configurations with language-specific overrides
- **Validation**: Compile-time and runtime config validation
- **Testing**: Configuration-based test generation
- **Documentation**: Auto-generate parser docs from config

## Example Usage
```bash
# Generate parser from config
cargo prism generate --config rust-parser.yml

# Validate configuration
cargo prism validate-config rust-parser.yml

# Test configuration against sample files
cargo prism test-config rust-parser.yml --samples tests/fixtures/
```

## Acceptance Criteria
- [ ] Design configuration schema (YAML/TOML)
- [ ] Implement `ParserConfig` struct and parsing
- [ ] Create `ConfigurableParser` with generic mapping logic
- [ ] Implement configuration validation system
- [ ] Support inheritance and composition
- [ ] Add hot-reloading capabilities
- [ ] Include comprehensive configuration testing
- [ ] Create migration tools from hardcoded parsers
- [ ] Generate documentation from configurations
- [ ] Integrate with `cargo-prism` CLI

## Priority
High - Enables rapid prototyping and community contributions
