### ISSUE TITLE
Build comprehensive template generation system

### ISSUE THREAD

**Issue by milliondreams** [rustic-ai/codeprism#31]
## Problem
While `cargo-prism new-parser` can scaffold basic parsers, we need a more sophisticated template system that can:
- Generate complex language-specific patterns
- Support multiple template variants
- Enable community template contributions
- Provide project-specific customizations

## Proposed Solution
Create a comprehensive template generation system with multiple tiers:

```bash
# Use built-in templates
cargo prism new-parser rust --template advanced-oop
cargo prism new-parser javascript --template functional-paradigm

# Use community templates
cargo prism new-parser python --template github:community/ml-focused

# Create custom templates
cargo prism template create my-company-standard
cargo prism template publish my-company-standard --registry private
```

### 1. Template Registry
```rust
pub struct TemplateRegistry {
    pub fn register_template(&mut self, template: Template) -> Result<()>;
    pub fn list_templates(&self, language: Option<&str>) -> Vec<TemplateInfo>;
    pub fn get_template(&self, name: &str) -> Result<Template>;
    pub fn fetch_remote(&self, url: &str) -> Result<Template>;
}
```

### 2. Template Engine
```rust
pub struct TemplateEngine {
    pub fn render_template(&self, template: &Template, context: &TemplateContext) -> Result<GeneratedCrate>;
    pub fn validate_template(&self, template: &Template) -> ValidationResult;
    pub fn preview_generation(&self, template: &Template, context: &TemplateContext) -> Preview;
}
```

### 3. Template Definition
```yaml
# template.yml
name: "advanced-oop"
description: "Template for object-oriented languages with inheritance"
version: "1.0.0"
author: "CodePrism Team"
language: "rust"

variables:
  - name: "language_name"
    type: "string"
    description: "Name of the target language"
    required: true
  - name: "supports_inheritance"
    type: "boolean"
    default: true
  - name: "supports_generics"
    type: "boolean"
    default: false

files:
  - path: "src/parser.rs"
    template: "templates/advanced_parser.rs.hbs"
    conditions:
      - "supports_inheritance == true"
  - path: "src/inheritance_mapper.rs"
    template: "templates/inheritance_mapper.rs.hbs"
    conditions:
      - "supports_inheritance == true"

node_mappings:
  class_declaration: "Class"
  interface_declaration: "Class"
  inheritance_clause: "Extends"

test_fixtures:
  - "fixtures/classes.{{ language_ext }}"
  - "fixtures/inheritance.{{ language_ext }}"
```

### 1. Language Paradigm Templates
- **Object-Oriented**: Classes, inheritance, polymorphism
- **Functional**: Functions, closures, immutability
- **Procedural**: Functions, modules, simple structures
- **Hybrid**: Multi-paradigm language support

### 2. Domain-Specific Templates
- **Systems Programming**: Memory management, unsafe operations
- **Web Development**: HTTP routes, frameworks, templating
- **Data Science**: Notebooks, data structures, analysis
- **Mobile Development**: Platform-specific patterns

### 3. Complexity Templates
- **Minimal**: Basic parsing with essential features
- **Standard**: Full specification compliance
- **Advanced**: Extended features and optimizations
- **Enterprise**: Full validation, monitoring, metrics

### 1. Conditional Generation
```handlebars
{{#if supports_async}}
pub async fn parse_async(&mut self, context: &ParseContext) -> Result<ParseResult> {
    // Async parsing implementation
}
{{/if}}

{{#each custom_node_types}}
{{snake_case this}}: NodeKind::{{pascal_case this}},
{{/each}}
```

### 2. Dynamic Node Mappings
```yaml
node_mappings:
  function_declaration: "Function"
  {{#if supports_methods}}
  method_declaration: "Method"
  {{/if}}
  {{#if supports_lambdas}}
  lambda_expression: "Function"
  {{/if}}
```

### 3. Language-Specific Optimizations
```rust
// Generated for high-performance languages
impl MemoryOptimizedParser {
    #[inline(always)]
    fn extract_node_fast(&self, node: &tree_sitter::Node) -> Option<NodeKind> {
        // Optimized extraction for performance-critical languages
    }
}
```

### 1. Template Marketplace
- Community-contributed templates
- Rating and review system
- Version management
- Security scanning

### 2. Template Validation
- Automated testing of generated parsers
- Compliance checking
- Performance benchmarking
- Security audit

### 3. Documentation Generation
- Auto-generated template documentation
- Usage examples
- Best practices guides
- Migration instructions

## Acceptance Criteria
- [ ] Design template definition schema (YAML/TOML)
- [ ] Implement `TemplateEngine` with Handlebars/Tera
- [ ] Create `TemplateRegistry` with local/remote support
- [ ] Build set of built-in templates for common patterns
- [ ] Add conditional generation capabilities
- [ ] Support variable substitution and validation
- [ ] Include template testing framework
- [ ] Create community template marketplace
- [ ] Add template security scanning
- [ ] Generate comprehensive documentation
- [ ] Integrate with `cargo-prism` CLI

## Template Examples
- **Rust Template**: Memory-safe systems programming
- **Python Template**: Dynamic typing with type hints
- **JavaScript Template**: Prototype-based OOP and functional
- **Java Template**: Classical OOP with generics
- **Go Template**: Structural typing and interfaces

## Priority
Medium - Enables advanced customization and community contributions
